# Generated by Django 5.0.2 on 2024-03-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(default=3, verbose_name="امتیاز"),
        ),
    ]
