# Generated by Django 5.0.2 on 2024-03-29 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0002_alter_review_rating"),
        ("product", "0016_boardgame_reviews"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productcomment",
            name="approved",
            field=models.BooleanField(default=False, verbose_name="تایید شده"),
        ),
        migrations.AddField(
            model_name="review",
            name="approved",
            field=models.BooleanField(default=False, verbose_name="تایید شده"),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("user", "product")},
        ),
    ]
