# Generated by Django 5.0.2 on 2024-02-24 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=127, verbose_name="تحویل گیرنده"),
                ),
                ("phone", models.CharField(max_length=11, verbose_name="شماره تماس")),
                ("address", models.TextField(verbose_name="نشانی کامل")),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="کد پستی"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
        ),
    ]
