# Generated by Django 5.0.2 on 2024-02-25 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "آدرس", "verbose_name_plural": "آدرس ها"},
        ),
    ]
