# Generated by Django 5.0.2 on 2024-02-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_address_is_active"),
    ]

    operations = [
    ]
