# Generated by Django 5.0.2 on 2024-02-25 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_address_city_remove_address_province"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={
                "ordering": ["-is_active"],
                "verbose_name": "آدرس",
                "verbose_name_plural": "آدرس ها",
            },
        ),
    ]
