# Generated by Django 5.0.2 on 2024-02-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_address_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="آدرس فعال"),
        ),
    ]
