# Generated by Django 5.0.2 on 2024-03-18 20:53

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_address_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="phone",
            field=models.CharField(
                max_length=11,
                validators=[apps.accounts.validators.validate_phone_number],
                verbose_name="شماره تماس",
            ),
        ),
    ]
