# Generated by Django 5.0.2 on 2024-04-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_user_groups_user_is_superuser_user_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="staff_status",
            field=models.BooleanField(
                default=False, verbose_name="داشتن تمام دسترسی ها"
            ),
        ),
    ]
