# Generated by Django 5.0.2 on 2024-02-21 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BoardGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=127, verbose_name="نام محصول")),
                ("description", models.TextField(verbose_name="توضیحات")),
                ("price", models.IntegerField(verbose_name="قیمت")),
                (
                    "discount",
                    models.SmallIntegerField(default=0, verbose_name="درصد تخفیف"),
                ),
                ("bgg_id", models.IntegerField()),
                ("side_description", models.TextField(verbose_name="توضیحات کنار عکس")),
                (
                    "player_count_min",
                    models.SmallIntegerField(verbose_name="حداقل تعداد بازیکنان"),
                ),
                (
                    "player_count_max",
                    models.SmallIntegerField(verbose_name="حداکثر تعداد بازیکنان"),
                ),
                ("time_min", models.SmallIntegerField(verbose_name="حداقل زمان بازی")),
                ("time_max", models.SmallIntegerField(verbose_name="حداکثر زمان بازی")),
                ("age", models.SmallIntegerField(verbose_name="حداقل سن بازیکنان")),
                ("complexity", models.FloatField(verbose_name="سختی بازی")),
            ],
            options={
                "verbose_name": "بردگیم",
                "verbose_name_plural": "بردگیم ها",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="products", verbose_name="تصویر"),
                ),
                ("featured", models.BooleanField(verbose_name="تصویر شاخص")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="product.boardgame",
                    ),
                ),
            ],
        ),
    ]
