# Generated by Django 5.0.2 on 2024-03-18 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_category_designer_mechanism_publisher_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "verbose_name": "تصویر محصول",
                "verbose_name_plural": "تصاویر محصول",
            },
        ),
        migrations.AddField(
            model_name="boardgame",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AlterField(
            model_name="boardgame",
            name="bgg_id",
            field=models.IntegerField(verbose_name="آیدی بردگیم گیک"),
        ),
        migrations.AlterField(
            model_name="boardgame",
            name="categories",
            field=models.ManyToManyField(
                to="product.category", verbose_name="دسته بندی(ها)"
            ),
        ),
        migrations.AlterField(
            model_name="boardgame",
            name="designers",
            field=models.ManyToManyField(
                to="product.designer", verbose_name="طراح(های) بازی"
            ),
        ),
        migrations.AlterField(
            model_name="boardgame",
            name="mechanisms",
            field=models.ManyToManyField(
                to="product.mechanism", verbose_name="مکانیزم(ها)"
            ),
        ),
        migrations.AlterField(
            model_name="boardgame",
            name="publisher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="boardgames",
                to="product.publisher",
                verbose_name="ناشر",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="product.boardgame",
                verbose_name="محصول",
            ),
        ),
    ]
