# Generated by Django 5.0.2 on 2024-03-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_productimage_options_boardgame_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="image",
        ),
        migrations.RemoveField(
            model_name="mechanism",
            name="image",
        ),
        migrations.AlterField(
            model_name="boardgame",
            name="categories",
            field=models.ManyToManyField(
                related_name="boardgames",
                to="product.category",
                verbose_name="دسته بندی(ها)",
            ),
        ),
        migrations.AlterField(
            model_name="boardgame",
            name="designers",
            field=models.ManyToManyField(
                related_name="boardgames",
                to="product.designer",
                verbose_name="طراح(های) بازی",
            ),
        ),
        migrations.AlterField(
            model_name="boardgame",
            name="mechanisms",
            field=models.ManyToManyField(
                related_name="boardgames",
                to="product.mechanism",
                verbose_name="مکانیزم(ها)",
            ),
        ),
    ]
