# Generated by Django 5.0.2 on 2024-03-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_remove_category_image_remove_mechanism_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardgame",
            name="rating",
            field=models.PositiveSmallIntegerField(
                default=3, verbose_name="امتیاز محصول"
            ),
        ),
    ]
