# Generated by Django 5.0.2 on 2024-03-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_boardgame_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardgame",
            name="rating",
            field=models.DecimalField(
                decimal_places=1, default=3, max_digits=2, verbose_name="امتیاز محصول"
            ),
        ),
    ]
