# Generated by Django 5.0.2 on 2024-03-20 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_alter_boardgame_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardgame",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 21, 2, 22, 19, 71597),
                verbose_name="تاریخ ایجاد محصول",
            ),
        ),
    ]
