# Generated by Django 5.0.2 on 2024-03-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_boardgame_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardgame",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="تاریخ ایجاد محصول"
            ),
        ),
    ]
