# Generated by Django 5.0.2 on 2024-03-26 19:27

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_alter_boardgame_created_at"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="boardgame",
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="boardgame",
            name="title",
            field=models.CharField(max_length=127, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=127, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="designer",
            name="title",
            field=models.CharField(max_length=127, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="mechanism",
            name="title",
            field=models.CharField(max_length=127, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="title",
            field=models.CharField(max_length=127, verbose_name="نام"),
        ),
    ]
