# Generated by Django 5.0.2 on 2024-03-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_alter_boardgame_managers_alter_boardgame_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardgame",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="designer",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="mechanism",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=255, null=True, unique=True
            ),
        ),
    ]
