# Generated by Django 5.0.2 on 2024-03-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_boardgame_slug_category_slug_designer_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designer",
            name="image",
            field=models.ImageField(upload_to="designers", verbose_name="تصویر"),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="image",
            field=models.ImageField(upload_to="publishers", verbose_name="تصویر"),
        ),
    ]
