# Generated by Django 5.0.2 on 2024-03-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_alter_designer_image_alter_publisher_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardgame",
            name="discount_expire_time",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="تاریخ انقضا تخفیف"
            ),
        ),
    ]
