# Generated by Django 5.0.2 on 2024-03-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_boardgame_discount_expire_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardgame",
            name="discount_expire_time",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="تاریخ انقضا تخفیف"
            ),
        ),
    ]
