# Generated by Django 5.0.2 on 2024-03-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0013_alter_boardgame_discount_expire_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boardgame",
            name="discount_expire_time",
        ),
        migrations.AddField(
            model_name="boardgame",
            name="visits",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="بازدیدها"
            ),
        ),
        migrations.AlterField(
            model_name="boardgame",
            name="rating",
            field=models.DecimalField(
                decimal_places=1,
                default=3,
                editable=0,
                max_digits=2,
                verbose_name="امتیاز محصول",
            ),
        ),
    ]
