# Generated by Django 5.0.2 on 2024-03-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0014_remove_boardgame_discount_expire_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardgame",
            name="featured",
            field=models.BooleanField(default=False, verbose_name="منتخب"),
        ),
    ]
