# Generated by Django 5.0.2 on 2024-03-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0015_boardgame_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardgame",
            name="reviews",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="تعداد بررسی ها"
            ),
        ),
    ]
