# Generated by Django 5.0.2 on 2024-03-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0016_boardgame_reviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardgame",
            name="sales",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="تعداد فروش"
            ),
        ),
    ]
