# Generated by Django 5.0.2 on 2024-04-09 14:57

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0017_boardgame_sales"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="designer",
            name="image",
        ),
        migrations.RemoveField(
            model_name="publisher",
            name="image",
        ),
        migrations.AlterField(
            model_name="boardgame",
            name="description",
            field=tinymce.models.HTMLField(verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="boardgame",
            name="side_description",
            field=tinymce.models.HTMLField(verbose_name="توضیحات کنار عکس"),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=tinymce.models.HTMLField(verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="designer",
            name="description",
            field=tinymce.models.HTMLField(verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="mechanism",
            name="description",
            field=tinymce.models.HTMLField(verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="description",
            field=tinymce.models.HTMLField(verbose_name="توضیحات"),
        ),
    ]
