# Generated by Django 5.0.2 on 2024-03-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomeBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="home/banners", verbose_name="تصویر بنر"
                    ),
                ),
                ("url", models.URLField(verbose_name="آدرس")),
            ],
            options={
                "verbose_name": "بنر کنار اسلایدر",
                "verbose_name_plural": "بنرهای کنار اسلایدر",
            },
        ),
        migrations.CreateModel(
            name="HomeSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="home/slides", verbose_name="تصویر اسلاید"
                    ),
                ),
                ("url", models.URLField(verbose_name="آدرس")),
            ],
            options={
                "verbose_name": "اسلاید",
                "verbose_name_plural": "اسلایدها",
            },
        ),
    ]
