# Generated by Django 5.0.2 on 2024-03-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homeslide",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="آدرس"),
        ),
    ]
