# Generated by Django 5.0.2 on 2024-04-05 07:00

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_homeslide_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", tinymce.models.HTMLField()),
                ("is_active", models.BooleanField(default=False, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "محتویات صفحه درباره ما",
                "verbose_name_plural": "محتویات صفحه درباره ما",
            },
        ),
    ]
