# Generated by Django 5.0.2 on 2024-02-25 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "محصول خریداری شده",
                "verbose_name_plural": "محصولات خریداری شده",
            },
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="order.order",
                verbose_name="کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.PositiveIntegerField(verbose_name="قیمت"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="product.boardgame",
                verbose_name="محصول",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveSmallIntegerField(verbose_name="تعداد"),
        ),
    ]
