# Generated by Django 5.0.2 on 2024-02-25 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_address_options"),
        ("order", "0002_alter_orderitem_options_alter_orderitem_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="addresses",
                to="accounts.address",
                verbose_name="آدرس",
            ),
        ),
    ]
