# Generated by Django 5.0.2 on 2024-02-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_alter_order_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
