# Generated by Django 5.0.2 on 2024-02-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_order_total_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("discount", models.PositiveSmallIntegerField(default=0)),
                ("quantity", models.SmallIntegerField(default=1)),
                ("expire_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
