# Generated by Django 5.0.2 on 2024-02-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_discountcode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discountcode",
            options={"verbose_name": "کد تخفیف", "verbose_name_plural": "کدهای تخفیف"},
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="discount",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="درصد تخفیف"
            ),
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="expire_date",
            field=models.DateTimeField(verbose_name="تاریخ انقضا"),
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="name",
            field=models.CharField(max_length=20, unique=True, verbose_name="متن کد"),
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="quantity",
            field=models.SmallIntegerField(default=1, verbose_name="تعداد"),
        ),
    ]
