# Generated by Django 5.0.2 on 2024-03-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_alter_discountcode_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discounted_price",
            field=models.PositiveIntegerField(
                default=0, verbose_name="قیمت پس از تخفیف"
            ),
        ),
    ]
