# Generated by Django 5.0.2 on 2024-03-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_order_discounted_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="price",
        ),
        migrations.AddField(
            model_name="order",
            name="total_original_price",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="مجموع کل اصلی"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="discounted_price",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="قیمت با تخفیف"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="original_price",
            field=models.PositiveIntegerField(default=1, verbose_name="قیمت اصلی"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="discounted_price",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="مجموع تخفیف"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.PositiveIntegerField(
                default=0, verbose_name="مجموع پس از نخفیف"
            ),
        ),
    ]
