# Generated by Django 5.0.2 on 2024-04-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0009_order_payment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount_code",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="کد تخفیف"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="ref_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="شماره پیگیری"
            ),
        ),
    ]
