# Generated by Django 5.0.2 on 2024-04-05 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0010_order_discount_code_order_ref_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DiscountCode",
        ),
    ]
