# Generated by Django 5.0.2 on 2024-04-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0011_delete_discountcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="discount_code",
        ),
        migrations.AddField(
            model_name="order",
            name="post_code",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="کد پیگیری پست"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending_approval", "در انتظار تایید"),
                    ("preparing", "در حال آماده سازی"),
                    ("post_delivered", "تحویل پست داده شده"),
                    ("received", "دریافت شده"),
                ],
                max_length=20,
                null=True,
                verbose_name="وضعیت سفارش",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="discounted_price",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                editable=False,
                null=True,
                verbose_name="مجموع تخفیف",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="پرداخت شده"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_date",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="تاریخ و ساعت پرداخت",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="ref_id",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=255,
                null=True,
                verbose_name="شماره پیگیری",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_original_price",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                editable=False,
                null=True,
                verbose_name="مجموع کل اصلی",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="مجموع پس از نخفیف"
            ),
        ),
    ]
