# Generated by Django 5.0.2 on 2024-04-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0013_alter_order_discounted_price_alter_order_is_paid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
        migrations.AddField(
            model_name="order",
            name="receiver_info",
            field=models.TextField(
                blank=True, null=True, verbose_name="اطلاعات گیرنده"
            ),
        ),
    ]
