# Generated by Django 5.0.2 on 2024-04-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0014_remove_order_address_order_receiver_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="post_price",
            field=models.PositiveIntegerField(default=0, verbose_name="هزینۀ پست"),
        ),
    ]
