# Generated by Django 5.0.2 on 2024-04-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0015_order_post_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("در انتظار تایید", "در انتظار تایید"),
                    ("در حال آماده سازی", "در حال آماده سازی"),
                    ("تحویل پست داده شده", "تحویل پست داده شده"),
                    ("دریافت شده", "دریافت شده"),
                ],
                max_length=20,
                null=True,
                verbose_name="وضعیت سفارش",
            ),
        ),
    ]
